version: "3.8"

services:
  web:
    build: .
    container_name: flask_docker_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    image: flask_docker_image
    command: python app.py

